# Generated by Django 4.0.6 on 2022-07-28 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=50)),
                ('date_of_creation', models.DateTimeField(auto_now_add=True)),
                ('e_date', models.DateField(auto_now_add=True)),
                ('desc', models.TextField()),
                ('p_limit', models.IntegerField()),
                ('brochure', models.ImageField(upload_to='')),
                ('Venue', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('desc', models.TextField(blank=True)),
                ('time', models.TimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=255)),
                ('c_about', models.TextField()),
                ('profile_pic', models.ImageField(upload_to='club')),
                ('events', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
