# Generated by Django 4.0.6 on 2022-08-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='e_date',
            field=models.DateField(verbose_name='Event Date'),
        ),
    ]
