# Generated by Django 4.0.6 on 2022-08-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Club',
        ),
    ]
