# Generated by Django 4.0.6 on 2022-08-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student'),
        ('event', '0002_event_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, null=True, to='users.student'),
        ),
    ]
