# Generated by Django 4.0.6 on 2022-07-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_club_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='e_type',
            field=models.CharField(default='College Fest', max_length=188, verbose_name='Event Type'),
        ),
        migrations.AddField(
            model_name='event',
            name='reg_fee',
            field=models.CharField(default='Free', max_length=100, verbose_name='Registration Fee'),
        ),
        migrations.AlterField(
            model_name='club',
            name='c_about',
            field=models.TextField(verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='club',
            name='c_name',
            field=models.CharField(max_length=255, verbose_name='Club Name'),
        ),
        migrations.AlterField(
            model_name='club',
            name='profile_pic',
            field=models.ImageField(upload_to='club', verbose_name='Profile Pic'),
        ),
        migrations.AlterField(
            model_name='event',
            name='brochure',
            field=models.ImageField(upload_to='', verbose_name='Event Poster'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_of_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of Creation'),
        ),
        migrations.AlterField(
            model_name='event',
            name='desc',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='e_date',
            field=models.DateField(auto_now_add=True, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='e_name',
            field=models.CharField(max_length=50, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='event',
            name='p_limit',
            field=models.IntegerField(verbose_name='Participant Limit'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='desc',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
