# Generated by Django 4.0.6 on 2022-07-28 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0003_event_e_type_event_reg_fee_alter_club_c_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='c_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
