# Generated by Django 4.0.6 on 2022-08-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_event_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='p_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Participant Limit'),
        ),
    ]
