# Generated by Django 4.0.6 on 2022-07-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_admin',
            new_name='is_staff',
        ),
        migrations.RemoveField(
            model_name='account',
            name='hide_email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='profile_image',
        ),
    ]
