# Generated by Django 4.0.6 on 2022-08-02 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(verbose_name='biography')),
                ('dept', models.CharField(max_length=233, verbose_name='Department')),
                ('year_of_passout', models.SmallIntegerField()),
                ('profile_pic', models.ImageField(blank=True, default='users/profile/default.png', null=True, upload_to=users.models.PathAndRename('users/profile/'))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
