# Generated by Django 4.0.6 on 2022-08-01 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_account_profile_image_account_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
