# Generated by Django 4.0.6 on 2022-08-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_year_of_passout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_passout',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
